import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { LoginComponent } from 'src/app/shared/dialogs/login/login.component';

@Component({
  selector: 'app-app-store',
  templateUrl: './app-store.component.html',
  styleUrls: ['./app-store.component.scss'],
})
export class AppStoreComponent implements OnInit {
  constructor(public dialog: MatDialog) {}

  ngOnInit(): void {}

  openloginDialog() {
    const dialogRef = this.dialog.open(LoginComponent, {
      width: '500px',
      height: '500px',
    });
    dialogRef.afterClosed().subscribe((result) => {});
  }

  apps:any[] = [
    {
      user_app_category_name: 'Accounts',
      data: [
        {
          user_app_id: 1,
          user_app_icon_name: 'string',
          user_app_icon_image_path: 'string',
          user_app_full_name: 'string',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'Accounts',
          user_app_category_name: 'Accounts',
          user_app_category_path: '100',
          user_app_category_id: 'id:100',
        },
      ],
    },
    {
      user_app_category_name: 'Security',
      data: [
        {
          user_app_id: 1,
          user_app_icon_name: 'string',
          user_app_icon_image_path: 'string',
          user_app_full_name: 'string',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'Security',
          user_app_category_name: 'Security',
          user_app_category_path: '200',
          user_app_category_id: 'id:200',
        },
        {
          user_app_id: 3,
          user_app_icon_name: 'string2',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string2',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'Security',
          user_app_category_name: 'Security',
          user_app_category_path: '200',
          user_app_category_id: 'id:200',
        },
      ],
    },
    {
      user_app_category_name: 'Communication Apps',
      data: [
        {
          user_app_id: 1,
          user_app_icon_name: 'Official Chat App',
          user_app_icon_image_path: 'string',
          user_app_full_name: 'string',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 2,
          user_app_icon_name: 'BoradCast',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string1',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 3,
          user_app_icon_name: 'Directory',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string2',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
      ],
    },
    {
      user_app_category_name: 'Admin Apps',
      data: [
        {
          user_app_id: 1,
          user_app_icon_name: 'Users Admin',
          user_app_icon_image_path: 'string',
          user_app_full_name: 'string',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 2,
          user_app_icon_name: ' User Login Session Data',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string1',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        }
      ],
    },
    {
      user_app_category_name: 'MD3',
      data: [
        {
          user_app_id: 1,
          user_app_icon_name: 'string',
          user_app_icon_image_path: 'string',
          user_app_full_name: 'string',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 2,
          user_app_icon_name: 'string1',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string1',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 3,
          user_app_icon_name: 'string2',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string2',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
      ],
    },
    {
      user_app_category_name: 'APP Management Console',
      data: [
        {
          user_app_id: 1,
          user_app_icon_name: 'Console Users Admin',
          user_app_icon_image_path: 'string',
          user_app_full_name: 'string',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 2,
          user_app_icon_name: 'Your Biz App Configuration',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string1',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 3,
          user_app_icon_name: 'User Category Management',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string2',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
      ],
    },
    {
      user_app_category_name: 'Human Resources (HR) Apps',
      data: [
        {
          user_app_id: 1,
          user_app_icon_name: 'Attendance + Leave App',
          user_app_icon_image_path: 'string',
          user_app_full_name: 'string',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 2,
          user_app_icon_name: 'Leave Request',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string1',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 3,
          user_app_icon_name: 'Expenses Reimbursement',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string2',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
      ],
    },
    {
      user_app_category_name: 'Productivity Apps',
      data: [
        {
          user_app_id: 1,
          user_app_icon_name: 'Calendar',
          user_app_icon_image_path: 'string',
          user_app_full_name: 'string',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 2,
          user_app_icon_name: 'Project Schedule',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string1',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 3,
          user_app_icon_name: 'Cloud File Storage',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string2',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
        {
          user_app_id: 4,
          user_app_icon_name: 'Block Social Media',
          user_app_icon_image_path: 'string1',
          user_app_full_name: 'string2',
          user_app_development_status: 1,
          user_app_category_location: 0,
          user_app_business_category_id: 'id:100',
          user_app_country_id: 1,
          custom_app_id: null,
          CategoryName: 'MD3',
          user_app_category_name: 'MD3',
          user_app_category_path: '300',
          user_app_category_id: 'id:300',
        },
      ],
    },
    
  ];
}
